### ISSUE TITLE
How to slow down the library ? 

### ISSUE THREAD

**Issue by Patriboom** [RobTillaart/DHTstable#18]
Hello, 
thanks for the library, it saved me from incompatibilies between dht.h and some other libraries in my project.

But still ... with ESP32-CAM connected to pin GPIO13 or GPIO12 It never gives back anything else than «Time out error »
Have I to use other pin or can we slow the DHTStable library down ?

**Comment by RobTillaart** [comment]
Thanks for the. Issue. 
I will look into it tomorrow.

**Comment by Patriboom** [comment]
Basically, i took you example code ( https://github.com/RobTillaart/DHTstable/tree/master/examples/dht22_test ) and tried it on ESP32-CAM AI-Thinker.

![ESP32cam_Pinout](https://user-images.githubusercontent.com/19801202/192124511-4fd9fd35-809c-499f-86d7-69f6dcc0b55b.png)


My code goes as this: 


```
#include <DHTStable.h>
#define DHTPIN 13        //I've tried:   12, 13, 14, 15, 16
const int DHTTYPE = 22;   //Valeurs possibles:  11 ou 22
float tempDHT;
float humiDHT;
DHTStable DHT;

struct {
    uint32_t total;
    uint32_t ok;
    uint32_t crc_error;
    uint32_t time_out;
    uint32_t connect;
    uint32_t ack_l;
    uint32_t ack_h;
    uint32_t unknown;
} counter = { 0,0,0,0,0,0,0,0};

void loop(){
  if ((millis() - lastTime) > timerDelay) {
    Serial.println("\n--------------------------------------------------------");

      uint32_t start = micros();
//      if (DHTTYPE == 22) {  
        int chk = DHT.read22(DHTPIN);
//      } else {
//        int chk = DHT.read11(DHTPIN);
//      }
      uint32_t stop = micros();
  
      counter.total++;
      switch (chk) {
      case DHTLIB_OK:
          counter.ok++;
          Serial.print("OK,\t");
          break;
      case DHTLIB_ERROR_CHECKSUM:
          counter.crc_error++;
          Serial.print("Checksum error,\t");
          break;
      case DHTLIB_ERROR_TIMEOUT:
          counter.time_out++;
          Serial.println("Délai dépassé en lecture de DHT");
          break;
      default:
          counter.unknown++;
          Serial.println("Erreur inconnue survenue sur DHT");
          break;
      }
    humiDHT = DHT.getHumidity();
    tempDHT = DHT.getTemperature();
}

```

Astonishly, there's nothing in your setup() {} but some Serial.prints  
Is there anytihing missing ? 

```

void setup()
{
    Serial.begin(115200);
    Serial.println(__FILE__);
    Serial.print("LIBRARY VERSION: ");
    Serial.println(DHTSTABLE_LIB_VERSION);
    Serial.println();
    Serial.println("Type,\tstatus,\tHumidity (%),\tTemperature (C)\tTime (us)");
}

```

Maybe have I to copy some lines from this setup part   ? 

Thanks.

**Comment by RobTillaart** [comment]
Good morning (Amsterdam Time zone here),

The **DHTstable** library is not tested with ESP32 by myself (and definitely not this variation).  
As the core "engine" is the same as **DHTNew** it should work in theory as that library is confirmed to work with ESP32.

However...
The protocol expects 5 bytes = 40 bits, + some handshake. A good transmission takes around 5 millis.
As the sensor is in control sending the bits, the protocol cannot be slowed down.

One of the problems with the DHT22 sensors is that they have a timing sensitive protocol, zeros and ones are clocked **by the sensor** to the processor as pulses of different length. If the main processor **interrupts** the clocking of the bits, it can miss a pulse causing timeouts. 

To handle the protocol on an ESP32 (and some other boards) the library has a function to disable interrupts during the transfer of bits from sensor to the processor. This function sets a flag to disable the interrupts around the critical part. It is not a 100% proof solution (as there exist non maskable interrupts) but it should work in most cases. 

Add this line to setup and see if it this helps with your ESP32
```cpp
DHT.setDisableIRQ(true);
```

**Comment by Patriboom** [comment]
Merci pour votre suivi détaillé et rapide.

La suggestion appliquée n'as donné les résultats escomptés.

Pouvez-vous confirmer que je configure bien mon matériel ? 
```

#define DHTPIN 13
...
int chk = DHT.read22(DHTPIN);

```

La valeur « 13 »  vient du GPIO13, tel que montré dans l'image ci-haut.
C'est ainsi qu'est configuré un BMP280 sur le même ESP32-CAM et le même projet

```
#define I2C_SDA 14
#define I2C_SCL 15
BME280 bme;

```
J'ai aussi ajouté la broche dans la commande de modification Wire
`
  Wire.begin(I2C_SDA, I2C_SCL, DHTPIN);
`


Avec ou sans 
`DHT.setDisableIRQ(true);`
j'obtiens le même résultat.

Merci quand même, ce semble bloqué pour l'instant.

**Comment by RobTillaart** [comment]
Pin number 13 should work, afaik it has no special purpose.

Do you have a pull up resistor on the data line of the sensor?. ESP32 is a 3V3 so a 2200 ohm or so could make the signal more squarish.

----

Wire.begin(I2C_SDA, I2C_SCL, DHTPIN);

This line does not make sense. The 3rd parameter is the i2c clock speed. Should be 100000 or 400000 or so.

The DHT22 is no i2c device so replace that line with

Wire.begin(I2C_SDA, I2C_SCL, 100000);

To be continued

**Comment by Patriboom** [comment]
Ok, nice to learn today again.  I did not associate such variables to speed, but to pin number.
I'll change it as you suggest.

**Comment by RobTillaart** [comment]
The Wire.begin() initializes the I2C port. It uses 2 pins for data en clock. That are parameter 1 and 2. 
The third is rhe I2C clock frequency. 

The speed 10000 is associated with the click pin of the I2C bus. Not with the DHTPIN.  you cannot set the speed of the DHT sensor as it is not an I2C device.

As told before the DHT sensor determines how fast the data is sent. You cannot configure this.

**Comment by Patriboom** [comment]
Thanks a lot for explainations.

**Comment by RobTillaart** [comment]
If you have time you might try to use the DHTNEW library. That one is more elaborated and is tested with an ESP32. All new developments will be done in that library.

Are you from Canada?

**Comment by Patriboom** [comment]
Ok thanks,
I'm from Québec.

**Comment by Patriboom** [comment]
Ok, thanks again Rob.

I installed DHTNEW and it seams to work well.

**Comment by Patriboom** [comment]
Confirmed:  DHTNEW works good with ESP32-CAM AI-Thinker  even in middle of others sensors of a larger project.

**Comment by RobTillaart** [comment]
Good to hear DHTNEW works well, 
I checked this morning and I was wrong that STABLE and NEW used the same core engine.
I might need to add a note to the readme.md
